### ISSUE TITLE
Section 2a - Starting the Solution (no indication how to start a solution or a project etc) 

### ISSUE THREAD

**Issue by perezca6576** [kwkraus/HOW-Sessions#2]
Just a suggestion. Perhaps this is something we are going to do live... but there is no idication how to start this step via visual studio.

suggesting adding couple of visual here... starting with solution and then project.
![image](https://user-images.githubusercontent.com/57501360/68678445-f1ff6280-052b-11ea-853f-04e9cfcf4411.png)

**Comment by kwkraus** [comment]
@perezca6576 The goal is to make the documentation (aka Instructor guide) as light as possible.  If there is an instructor that doesn't know how to create a project/solution prior to adding a new entity class... we're in trouble, so the idea is that this is obvious and doesn't need explaining.  does that make sense?   remember, this is not a guide for students, but a script on how the instructor should work and what content to touch on
