### ISSUE TITLE
Section 2a - Layout and RenderScripts etc.

### ISSUE THREAD

**Issue by perezca6576** [kwkraus/HOW-Sessions#3]
because this is our first view instance, we to brief on what partials views are and the concept behind it
Probably just adding the URL for additional details

[Resource](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-3.0)

![image](https://user-images.githubusercontent.com/57501360/68678715-77831280-052c-11ea-8e27-15c9a591e821.png)

**Comment by kwkraus** [comment]
@perezca6576 if you think we need a bullet point to "guide" instructor to touch on what a partial view is, absolutely.  

now that i think of it, perhaps that should be part of the "Working with Pages" session?

**Comment by kwkraus** [comment]
@perezca6576 would you have time to look at this?  also, the newest way we recommend are [View Components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1).  can you tell me what you'd like to see for our Working with Pages sections?

**Comment by kwkraus** [comment]
this is no longer a priority
