### ISSUE TITLE
section 2a -  section for prerequisite.

### ISSUE THREAD

**Issue by perezca6576** [kwkraus/HOW-Sessions#4]
Probably be good to have a small section for prerequisite. a little "_knowledge of HTML will help to understand the Razor syntax etc_"..

![image](https://user-images.githubusercontent.com/57501360/68679961-d3e73180-052e-11ea-8e5f-7099a0b4e528.png)

**Comment by kwkraus** [comment]
@perezca6576 we are going to have a prerequisites section for the whole HOW Session that should encompass this need for knowledge.  I think we'll be covered there
