### ISSUE TITLE
section 2a - Add resource URL

### ISSUE THREAD

**Issue by perezca6576** [kwkraus/HOW-Sessions#5]
is onGet inherance of PageModel? just having the Resouce URL will be helpful to support the statements.
![image](https://user-images.githubusercontent.com/57501360/68680227-54a62d80-052f-11ea-8dd5-da5ff48755a1.png)

**Comment by kwkraus** [comment]
@perezca6576 when you say resource URL, are you talking about a doc.microsoft.com link to support how the OnGet() works?   if there is one, we can definitely add it for the instructor to use when discussing this area

**Comment by perezca6576** [comment]
yes. that is correct Kevin. I was talking about MS URL I will look into and provide it

**Comment by kwkraus** [comment]
@perezca6576 any luck in finding a formal doc from MSFT on this?

**Comment by kwkraus** [comment]
leave to instructor to explain
