### ISSUE TITLE
3- Many-to-Many (just recommendation)

### ISSUE THREAD

**Issue by perezca6576** [kwkraus/HOW-Sessions#7]
@kwkraus, I am still working on this module. One area I see devs/clients struggling with is understanding the many-to-many pattern using Entity framework. I am adding this issue as a suggestion to add a many-to-many model class and demostrate how they are associated in the Entityframework context. This is a great value and does not take much time to add in code.

**Comment by kwkraus** [comment]
@perezca6576 The main goal of working with Data session is to understand EF Core at a high level...  Context/Entities/Migrations/etc.  

My goal was to have a more detailed HOW Session on EF Core where these concepts can be introduced.   What are your thoughts?

**Comment by perezca6576** [comment]
@kwkraus because we are using Entity Framework, it probably be good to reference a section for "Relationships". I think a Ref will be sufficient (this topic can be too long). Take a look at this resource:

https://docs.microsoft.com/en-us/ef/core/modeling/relationships

**Comment by kwkraus** [comment]
@perezca6576  I think it's a good idea, but we need to introduce a relationship for this to make sense.  right now, it is a lone product entity, perhaps we can introduce a category or tags that can be attached to a property?

**Comment by perezca6576** [comment]
@kwkraus thanks! per our conversation during meeting. it makes sense to take this as an extension of the module. Adding relationships and context entities can be a lot to covered. Closing this issue for now.
